# Generated by Django 5.0.1 on 2024-01-09 08:49

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import users.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='mobiletask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('price', models.PositiveBigIntegerField()),
                ('memory', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='mobiles')),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('blog_date', models.DateField()),
                ('poster', models.ImageField(upload_to='movie')),
                ('release_date', models.DateField()),
                ('story', models.TextField()),
                ('review', models.TextField()),
                ('movie_rating', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='registermodel',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_no', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10), users.validators.validate_phone_no])),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('comment', models.TextField()),
                ('comment_date', models.DateField(auto_now=True)),
                ('user_rating', models.DecimalField(decimal_places=1, max_digits=5)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.movie')),
            ],
        ),
    ]
